language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
install:
  - export MAVEN_HOME=/usr/local/maven-3.5.0
  - ./src/compile-and-clean-test-projects.sh

script:
  - mvn clean test

after_success:
  - mvn clean test jacoco:report coveralls:report
  - ./.travis/travis-deploy.sh

branch:
  only:
    - master