name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Setup Maven Settings
        run: cp .travis/travis-settings.xml $HOME/.m2/settings.xml
      - name: Publish package
        run: mvn deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_TESTRUNNER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_TESTRUNNER_PASSWORD }}