name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn install -DskipTests
      - name: Export Maven Home
        run: export MAVEN_HOME=/usr/local/maven-3.5.0
      - name: Prepare resources binaries
        run: ./src/compile-and-clean-test-projects.sh
      - name: Test with Maven
        run: mvn test

