name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 8 ,  11 , 17, 21 , 22]

    steps:
      - uses: actions/checkout@v3.0.0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Build with Maven
        run: ./src/update-classes-in-resources.sh
      - name: Prepare resources binaries
        run: ./src/compile-and-clean-test-projects.sh
      - name: Export MAVEN_HOME, run tests and collect coverage
        run: export MAVEN_HOME=`mvn --version | grep 'Maven home' | sed -e 's/Maven h.* //'` && echo "🎉 ${MAVEN_HOME}" && mvn test jacoco:report
      - name: Report coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
