name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: ./src/update-classes-in-resources.sh
      - name: Export Maven Home
        run: export MAVEN_HOME=`mvn --version | grep 'Maven home' | sed -e 's/Maven h.* //'` && echo "🎉 ${MAVEN_HOME} "
      - name: Prepare resources binaries
        run: ./src/compile-and-clean-test-projects.sh
      - name: Test and Coverage with Maven
        run: mvn test jacoco:report
      - name: Report coverage to Codecov
        uses: codecov/codecov-action@v1.5.2
