name: Publish latest build

on:
  workflow_dispatch:
  push:
      branches: [master]

jobs:
  deploy:
    if: ${{ github.repository == 'STAMP-project/test-runner' }}
    name: 'Publish package'
    runs-on: ubuntu-latest

    steps:
      - name: Wait for tests to pass
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          # Must be same as this job's name
          # Reference: https://github.com/lewagon/wait-on-check-action#running-workflow-name
          running-workflow-name: 'Publish package'
          repo-token: ${{ secrets.TOKEN_GITHUB }}
      - uses: actions/checkout@v3.0.0
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Start deployment
        env:
          OSS_TESTRUNNER_USERNAME: ${{ secrets.OSS_TESTRUNNER_USERNAME }}
          OSS_TESTRUNNER_PASSWORD: ${{ secrets.OSS_TESTRUNNER_PASSWORD }}
        run: ./.buildscript/deploy_to_maven.sh
